FROM partlab/ubuntu-jenkins 
RUN  add-apt-repository -y  ppa:cwchien/gradle && apt-get update && apt-get -y install gradle-2.14.1
RUN  apt-get update && apt-get upgrade -y &&  apt-get install -y docker.io 
