package br.com.mystudies.seleninum;

public class TODO {

	// TODO: docker in docker network to access
	// TODO: fix problems of navigation in spring security
	// TODO: add simple home page
	// TODO: task run image remote
	// TODO: analyze the https://github.com/spring-guides/gs-securing-web/blob/master/complete/src/test/java/hello/ApplicationTests.java
	// TODO: Selininum
	// TODO: improve the readme of 8-jre-alpine-bash with explanation about facilities run one dist generated by gradle....    
}
