package br.com.mystudies.seleninum;

public class TODO {

	// TODO: docker in docker network to access
	// TODO: Unit test ( TDD ) AuthenticationProvider
	// TODO: task run image remote
	// TODO: analyze the https://github.com/spring-guides/gs-securing-web/blob/master/complete/src/test/java/hello/ApplicationTests.java
	// TODO: Selininum
	// TODO: JMeter https://dzone.com/articles/how-to-easily-automate-performance-tests-in-jenkin?edition=220224&utm_source=Spotlight&utm_medium=email&utm_campaign=devops%202016-10-07
	// TODO: improve the readme of 8-jre-alpine-bash with explanation about facilities run one dist generated by gradle....

/*
 *
* Selenium
* PhantomJS
* JUnit
* Gradle
* Test (Unit, Integration, Performance)
* Docker
* Jmeter
* Java
 */


}
